name: flutter_weather_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  core:
    path: ./core
  cupertino_icons: ^1.0.2
  data:
    path: ./data
  domain:
    path: ./domain
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.4.20
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  get_secure_storage: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - environment/
