name: core
description: Module represent core layer.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.4.20
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_secure_storage: ^1.0.5
    
  logger: ^2.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true
