name: domain
description: Module represent domain layer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  core:
    path: ../core
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  freezed: ^2.5.2
  mocktail: ^1.0.3
  test: ^1.24.9
